### ISSUE TITLE
Instagram Like Bot

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/instagram-on-steroids#1]
## Value Proposition

As a Influencer
I want to be active on Instagram, without being active
so that I can relax and still have a growth in followership

## Description

We need a bot, which auto-likes content in given hashtags.
So we getting positive weight values for the Instagram algorithm in order to gain followers in a organic fashion.

## Acceptance Critera

- [ ] Likes posts in given Hashtags
- [ ] Does it in random intervals to act human-like

## Tasks

- [ ] Evaluate if using screen reading/scraping or the official api
- [ ] Connect with the Instagram Account
- [ ] Create Config Variables
- [ ] Set env data
- [ ] Create random interval handling with min/max times
- [ ] Create a range of daily activity to avoid static daily likes
- [ ] Host bot either on RasPi or heroku
- [ ] run

## Complexity Weight

5
